"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var car_1 = require("./car");
var game_1 = require("./game");
var game = new game_1.Game();
var car1 = new car_1.Car("Clio IV", "Renault", "Black", 2017);
var car2 = new car_1.Car("A5", "Audi", "Grey", 2020);
var car3 = new car_1.Car("Roma", "Ferrari", "Red", 2023);
var car4 = new car_1.Car("Chiron", "Bugatti", "Blue", 2021);
game.addCar(car1);
game.addCar(car2);
game.addCar(car3);
game.addCar(car4);
game.start();
